### PR TITLE
2.0.0 Update

### PR DESCRIPTION
**Pull request by joshgarde**
- Version bump to 2.0.0 marking next changes as breaking
- Default SSL verification to enabled
- Fix cfg parsing
- Add get_job_by_id method

### CODE REVIEW

**Comment by joshgarde** [comment]
@mcayanan @pymonger @DustinKLo Could you take a look at this?

**Review by mcayanan — DISMISSED** [review]
LGTM. Okay with you too @pymonger ?

**Review by mcayanan — APPROVED** [review]
LGTM. @pymonger you good with this too?

**Review by pymonger — APPROVED** [review]
LGTM

**Pull request merged**
