### PR TITLE
HC-473: Expose publish_overwrite_ok in submit_job

### PR DESCRIPTION
**Pull request by joshgarde**
Part of HC-473 work

### CODE REVIEW

**Review by pymonger — DISMISSED** [review]
LGTM but let's get another pair of eyes.

**Review by mcayanan — DISMISSED** [review]
LGTM

**Review by DustinKLo — APPROVED** [review]

**Comment by DustinKLo** [comment]
we should bump the version in `setup.py`

**Review by DustinKLo — DISMISSED** [review]
we should bump the version in `setup.py`

**Review by pymonger — APPROVED** [review]

**Review by DustinKLo — APPROVED** [review]

**Pull request merged**
